apiVersion: v1
kind: ConfigMap
metadata:
  name: ace-context
data:
  aceEnvVersion: {{ .Values.aceContext.aceEnvVersion }}
  ace-context.yaml: |
    aceEnvVersion: {{ .Values.aceContext.aceEnvVersion }}
    domain: {{ .Values.aceContext.domain }}
    domainExternal: {{ .Values.aceContext.domainExternal }}
    storageClass:
      db: {{ .Values.aceContext.storageClass.db }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: version-badge
data:
  version-badge-template.gotmpl: |
    <svg xmlns="http://www.w3.org/2000/svg" width="100" height="20">
        <linearGradient id="b" x2="0" y2="100%">
            <stop offset="0" stop-color="#ccc" stop-opacity=".1"/>
            <stop offset="1" stop-opacity=".1"/>
        </linearGradient>
        <mask id="a">
            <rect width="100" height="20" rx="3" fill="#fff"/>
        </mask>
        <g mask="url(#a)">
            <path fill="#555" d="M0 0 h40 v20 H0 z"/>
            <path fill="#3973BA" d="M40 0 h100 v20 H40 z"/>
            <path fill="url(#b)" d="M0 0 h100 v20 H0 z"/>
        </g>
        <g fill="#fff" text-anchor="middle" font-family="DejaVu Sans,Verdana,Geneva,sans-serif" font-size="10">
            <text x="20" y="15" fill="#111111" fill-opacity=".3">ACE</text>
            <text x="20" y="14">ACE</text>
            <text x="70" y="15" fill="#010101" fill-opacity=".3">v{{ "{{ .AceEnvVersion }}" }}</text>
            <text x="70" y="14">v{{ "{{ .AceEnvVersion }}" }}</text>
        </g>
    </svg>

