{{- if .Values.virtualservice.enabled -}}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "gohtmx.fullname" . }}
spec:
  gateways:
  {{- toYaml .Values.virtualservice.gateways | nindent 2 }}
  hosts:
  {{- toYaml .Values.virtualservice.hosts | nindent 2 }}
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 8080
        host: {{ include "gohtmx.fullname" . }}
{{- end }}
