apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: gohtmx
  name: gohtmx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gohtmx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gohtmx
    spec:
      containers:
      - image: "{{ .Values.image }}:{{ .Values.tag }}"
        name: gohtmx
        resources: {}
status: {}
