apiVersion: v1
kind: Service
metadata:
  labels:
    app: gohtmx
  name: gohtmx
spec:
  ports:
  - name: http
    nodePort: 31080
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: gohtmx
  type: NodePort

